[workspace]
members = ["shared", "windows", "macos"]
resolver = "2"

[workspace.package]
version = "0.9.2"
authors = ["KraftPixel"]
edition = "2021"

[profile.release]
opt-level = "s"
lto = true
strip = true
