[package]
name = "savemyeyes-shared"
version = "0.9.2"
description = "Shared types and logic for SaveMyEyes"
authors = ["KraftPixel"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
ureq = "2"
